// File generated by Invisible Jacc version 1.1.
// Invisible Jacc is Copyright 1997-1998 Invisible Software, Inc.

package invisible.jacc.ex2;

import invisible.jacc.parse.ScannerTable;
import invisible.jacc.util.ArrayRLE;

public class Ex2GrammarScannerTable extends ScannerTable
{

    // The number of different character categories.

    private static final int gen_categoryCount = 11;

    // The character set size.

    private static final int gen_charSetSize = 256;

    // The character category table.

    private static byte[] gen_categoryTable = null;
    private static short[] rle_categoryTable = 
    {256, 2048, 7, 10, 0, 7, 9, 4352, 7, 1536, 2, 3, 0, 4, 0, 5, 0, 8, 2310, 0,
    1, -15616};

    // The number of tokens.

    private static final int gen_tokenCount = 8;

    // The token parameters.

    private static final int[] gen_tokenParam = 
    {1, 2, 3, 4, 5, 6, 0, 0};

    // The number of tokens that have a right context.

    private static final int gen_contextCount = 0;

    // Context number table.

    private static final int[] gen_contextNumber = 
    {0, 0, 0, 0, 0, 0, 0, 0};

    // The number of start conditions for the forward DFA.

    private static final int gen_conditionCount = 1;

    // The number of states in the forward DFA.

    private static final int gen_fwdStateCount = 13;

    // The number of recognition codes in the forward DFA.

    private static final int gen_fwdRecognitionCount = 9;

    // Forward DFA initial state table.

    private static final int[] gen_fwdInitialState = 
    {1};

    // Forward DFA transition table.

    private static short[][] gen_fwdTransitionTable = null;
    private static short[] rle_fwdTransitionTable = 
    {13, 11, -32502, 13, 11, 13, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 11, -32502, 13, 11,
    -32502, 13, 11, -32502, 13, 11, -32502, 13, 11, -32502, 13, 11, -32507, 13, 7, -32509, 13, 11, -32506, 13,
    8, 9, -32511, 13, 11, -32505, 13, 12, -32511, 13, 11, -32503, 13, 11, 11, -32502, 13, 11, -32504, 12,
    -32511, 13};

    // Forward DFA recognition table.

    private static final int[] gen_fwdRecognitionTable = 
    {0, 1, 2, 3, 4, 5, 6, 7, 1, 0, 8, 8, 1};

    // Forward DFA token list.

    private static final int[] gen_fwdTokenListLength = 
    {0, 1, 1, 1, 1, 1, 1, 1, 1};

    private static final int[][] gen_fwdTokenList = 
    {
        {},
        {6},
        {0},
        {1},
        {2},
        {3},
        {4},
        {5},
        {7}
    };

    // Forward DFA context split table.

    private static boolean[][] gen_fwdContextSplit = null;
    private static byte[] rle_fwdContextSplit = 
    {0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

    // The number of states in the reverse DFA.

    private static final int gen_revStateCount = 1;

    // The number of recognition codes in the reverse DFA.

    private static final int gen_revRecognitionCount = 1;

    // Reverse DFA transition table.

    private static short[][] gen_revTransitionTable = null;
    private static short[] rle_revTransitionTable = 
    {1, 11, -32502, 1};

    // Reverse DFA recognition table.

    private static final int[] gen_revRecognitionTable = 
    {0};

    // Reverse DFA context split table.

    private static boolean[][] gen_revContextSplit = null;
    private static byte[] rle_revContextSplit = 
    {0, 1, 0, 0};

    // The names of start conditions.

    private static final String[] gen_conditionNames = 
    {
        "%%normal"
    };

    // The names of tokens.

    private static final String[] gen_tokenNames = 
    {
        ";",
        "(",
        ")",
        "+",
        "-",
        "number",
        "whiteSpace",
        "lineEnd"
    };

    // The link name for each token.

    private static final String[] gen_tokenLink = 
    {
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    };




    // RLE decoding function

    private static synchronized void decodeRLE ()
    {
        if (gen_categoryTable == null)
        {
            gen_categoryTable = ArrayRLE.byteRLEToByte1D (rle_categoryTable);
            rle_categoryTable = null;
        }

        if (gen_fwdTransitionTable == null)
        {
            gen_fwdTransitionTable = ArrayRLE.shortRLEToShort2D (rle_fwdTransitionTable);
            rle_fwdTransitionTable = null;
        }

        if (gen_fwdContextSplit == null)
        {
            gen_fwdContextSplit = ArrayRLE.booleanRLEToBoolean2D (rle_fwdContextSplit);
            rle_fwdContextSplit = null;
        }

        if (gen_revTransitionTable == null)
        {
            gen_revTransitionTable = ArrayRLE.shortRLEToShort2D (rle_revTransitionTable);
            rle_revTransitionTable = null;
        }

        if (gen_revContextSplit == null)
        {
            gen_revContextSplit = ArrayRLE.booleanRLEToBoolean2D (rle_revContextSplit);
            rle_revContextSplit = null;
        }

        return;
    }




    // Constructor installs the generated tables into the ScannerTable

    public Ex2GrammarScannerTable ()
    {
        super ();

        // Decode the run-length-encoded tables

        decodeRLE ();

        // Copy scanning tables into the ScannerTable superclass

        _categoryCount = gen_categoryCount;
        _charSetSize = gen_charSetSize;
        _categoryTable = gen_categoryTable;
        _tokenCount = gen_tokenCount;
        _tokenParam = gen_tokenParam;
        _contextCount = gen_contextCount;
        _contextNumber = gen_contextNumber;
        _conditionCount = gen_conditionCount;
        _fwdStateCount = gen_fwdStateCount;
        _fwdRecognitionCount = gen_fwdRecognitionCount;
        _fwdInitialState = gen_fwdInitialState;
        _fwdTransitionTable = gen_fwdTransitionTable;
        _fwdRecognitionTable = gen_fwdRecognitionTable;
        _fwdTokenListLength = gen_fwdTokenListLength;
        _fwdTokenList = gen_fwdTokenList;
        _fwdContextSplit = gen_fwdContextSplit;
        _revStateCount = gen_revStateCount;
        _revRecognitionCount = gen_revRecognitionCount;
        _revTransitionTable = gen_revTransitionTable;
        _revRecognitionTable = gen_revRecognitionTable;
        _revContextSplit = gen_revContextSplit;

        // Copy dynamic-link tables into the ScannerTable superclass

        _conditionNames = gen_conditionNames;
        _tokenNames = gen_tokenNames;
        _tokenLink = gen_tokenLink;

        return;
    }


}

